# Introduction to Pandas

## Installing and Using Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.5'

## Pandas Series Object

In [4]:
data = pd.Series([0.1, 0.2, 0.3, 0.4, 0.5])
data

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [5]:
data.values

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [6]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
data

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [8]:
data[0]

np.float64(0.1)

In [9]:
data[1:4]

1    0.2
2    0.3
3    0.4
dtype: float64

In [10]:
data = pd.Series([0.1, 0.2, 0.3, 0.4, 0.5], index=['a', 'b', 'c', 'd', 'e'])
data

a    0.1
b    0.2
c    0.3
d    0.4
e    0.5
dtype: float64

In [12]:
data['b':'e']

b    0.2
c    0.3
d    0.4
e    0.5
dtype: float64

In [14]:
data[1:4]

b    0.2
c    0.3
d    0.4
dtype: float64

## Series as specialized Dictionaries

In [4]:
student_dict = {
    'name': 'Alice',
    'age': 21,
    'city': 'New York'
}

student_series = pd.Series(student_dict)
student_series

name       Alice
age           21
city    New York
dtype: object

In [5]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}
population_series = pd.Series(population_dict)
population_series

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [6]:
# explicit index
population_series['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

In [7]:
# implicit index
population_series[1:4]

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

## Constructing Series Objects

In [11]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [12]:
pd.Series(5, index=[10, 20, 30])

10    5
20    5
30    5
dtype: int64

In [13]:
pd.Series({
    1: 'a',
    2: 'b',
    3: 'c'
})

1    a
2    b
3    c
dtype: str

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array

In [4]:
area_dict = {
    'California': 423967, 
    'Texas': 695662, 
    'New York': 141297,
    'Florida': 170312, 
    'Illinois': 149995
}

area_series = pd.Series(area_dict)
area_series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [8]:
states = pd.DataFrame({
    'population': population_series,
    'area': area_series
})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [10]:
states.population['California']

np.int64(38332521)

In [14]:
print('New York Population:',states.population['New York'])

New York Population: 19651127

In [15]:
print('Illinois Area:',states.area['Illinois'])

Illinois Area: 149995

In [20]:
# slicing
# states.population[0:3]
states.population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

## DataFrame as a specialized dictionary

### From a single Series Object

In [21]:
pd.DataFrame(population_series, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135