# Merge and Join

In [1]:
import pandas as pd
import numpy as np

## Categories of Join

### One-to-One Joins

In [10]:
df1 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'departments': ['Accounting', 'Engineering', 'Engineering', 'HR'],
})

df2 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'hire_date': [2004, 2006, 2008, 2010],
})

display(df1, df2)

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

In [12]:
df3 = pd.merge(df1, df2, on='employee')
df3

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

### Many-to-One Joins

In [17]:
df4 = pd.DataFrame({
    'departments': ['Accounting', 'Engineering', 'Engineering', 'HR'],
    'supervisor': ['Carly', 'Guido', 'Steve', 'Melody'],
})

display(df3, df4)

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

   departments supervisor
0   Accounting      Carly
1  Engineering      Guido
2  Engineering      Steve
3           HR     Melody

In [18]:
df5 = pd.merge(df3, df4)
df5

  employee  departments  hire_date supervisor
0    Mercy   Accounting       2004      Carly
1     Mary  Engineering       2006      Guido
2     Mary  Engineering       2006      Steve
3     Mark  Engineering       2008      Guido
4     Mark  Engineering       2008      Steve
5  Maureen           HR       2010     Melody

### Many-to-Many Joins

In [23]:
df6 = pd.DataFrame({
    'departments': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
    'skills': ['Math', 'Software', 'Presentation', 'Math', 'Communication', 'Spreadsheet'],
})

display(df4, df6, pd.merge(df4, df6))

   departments supervisor
0   Accounting      Carly
1  Engineering      Guido
2  Engineering      Steve
3           HR     Melody

   departments         skills
0   Accounting           Math
1   Accounting       Software
2  Engineering   Presentation
3  Engineering           Math
4           HR  Communication
5           HR    Spreadsheet

   departments supervisor         skills
0   Accounting      Carly           Math
1   Accounting      Carly       Software
2  Engineering      Guido   Presentation
3  Engineering      Guido           Math
4  Engineering      Steve   Presentation
5  Engineering      Steve           Math
6           HR     Melody  Communication
7           HR     Melody    Spreadsheet

## Specification of the Merge Key

In [25]:
display(df1, df2)

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

In [28]:
display(df1, df2, pd.merge(df1, df2, on='employee'))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

### The left_on and right_on Keywords

In [33]:
df3 = pd.DataFrame({
    'name': ['Bob', 'Mercy', 'Mary', 'Mark'],
    'salary': [70000, 10000, 50000, 30000]
})

display(df1, df3, pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

  employee  departments   name  salary
0    Mercy   Accounting  Mercy   10000
1     Mary  Engineering   Mary   50000
2     Mark  Engineering   Mark   30000

#### Using drop() to drop desired columns

In [36]:
display(df1, df3, pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

  employee  departments  salary
0    Mercy   Accounting   10000
1     Mary  Engineering   50000
2     Mark  Engineering   30000

### The left_index and right_index Keywords

In [39]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

display(df1a, df2a)

          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

          hire_date
employee
Mercy          2004
Mary           2006
Mark           2008
Maureen        2010

In [40]:
display(df1a, df2a, pd.merge(df1a, df2a, left_index=True, right_index=True))

          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

          hire_date
employee
Mercy          2004
Mary           2006
Mark           2008
Maureen        2010

          departments  hire_date
employee
Mercy      Accounting       2004
Mary      Engineering       2006
Mark      Engineering       2008
Maureen            HR       2010

In [41]:
df1a.join(df2a)

          departments  hire_date
employee
Mercy      Accounting       2004
Mary      Engineering       2006
Mark      Engineering       2008
Maureen            HR       2010

In [42]:
display(df1a, df3, pd.merge(df1a, df3, left_index=True, right_on='name'))

          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

   departments   name  salary
1   Accounting  Mercy   10000
2  Engineering   Mary   50000
3  Engineering   Mark   30000

## Specifying Set Arithmetic for Joins

In [47]:
df6 = pd.DataFrame({
    'names': ['Peter', 'Mary', 'Paul'],
    'food': ['fish', 'beans', 'bread']
})

df7 = pd.DataFrame({
    'names': ['Mary', 'Paul'],
    'drink': ['wine', 'beer']
})

In [48]:
display(df6, df7, pd.merge(df6, df7))

   names   food
0  Peter   fish
1   Mary  beans
2   Paul  bread

  names drink
0  Mary  wine
1  Paul  beer

  names   food drink
0  Mary  beans  wine
1  Paul  bread  beer

In [49]:
pd.merge(df6, df7, how='inner')

  names   food drink
0  Mary  beans  wine
1  Paul  bread  beer

In [50]:
display(df6, df7, pd.merge(df6, df7, how='outer'))

   names   food
0  Peter   fish
1   Mary  beans
2   Paul  bread

  names drink
0  Mary  wine
1  Paul  beer

   names   food drink
0   Mary  beans  wine
1   Paul  bread  beer
2  Peter   fish   NaN

In [51]:
display(df6, df7, pd.merge(df6, df7, how='left'))

   names   food
0  Peter   fish
1   Mary  beans
2   Paul  bread

  names drink
0  Mary  wine
1  Paul  beer

   names   food drink
0  Peter   fish   NaN
1   Mary  beans  wine
2   Paul  bread  beer

In [52]:
display(df6, df7, pd.merge(df6, df7, how='right'))

   names   food
0  Peter   fish
1   Mary  beans
2   Paul  bread

  names drink
0  Mary  wine
1  Paul  beer

  names   food drink
0  Mary  beans  wine
1  Paul  bread  beer

### Overlapping Column Names

In [54]:
df8 = pd.DataFrame({
    'names': ['Peter', 'Mary', 'Paul'],
    'food': ['fish', 'beans', 'bread']
})

df9 = pd.DataFrame({
    'names': ['Mary', 'Paul'],
    'food': ['fish', 'beans']
})

In [56]:
display(df8, df9, pd.merge(df8, df9, on='names'))

   names   food
0  Peter   fish
1   Mary  beans
2   Paul  bread

  names   food
0  Mary   fish
1  Paul  beans

  names food_x food_y
0  Mary  beans   fish
1  Paul  bread  beans

## Example: US States Data

In [14]:
pop = pd.read_csv('data/state-population.csv')
ares = pd.read_csv('data/state-areas.csv')
abbrevs = pd.read_csv('data/state-abbrevs.csv')

In [15]:
pop.info()

<class 'pandas.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   str
 1   ages          2544 non-null   str
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 99.6 KB

In [16]:
display(pop.head(), ares.head(), abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [56]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged.head()

  state/region     ages  year  population   state abbreviation
0           AK    total  1990    553290.0  Alaska           AK
1           AK  under18  1990    177502.0  Alaska           AK
2           AK    total  1992    588736.0  Alaska           AK
3           AK  under18  1991    182180.0  Alaska           AK
4           AK  under18  1992    184878.0  Alaska           AK

In [58]:
merged_1 = merged.drop('abbreviation', axis=1).head()
merged_1.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [60]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
abbreviation    96
dtype: int64

In [61]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   str
 1   ages          2544 non-null   str
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
 4   state         2448 non-null   str
 5   abbreviation  2448 non-null   str
dtypes: float64(1), int64(1), str(4)
memory usage: 166.0 KB

In [62]:
merged[merged['population'].isnull()].head()

     state/region     ages  year  population state abbreviation
1872           PR  under18  1990         NaN   NaN          NaN
1873           PR    total  1990         NaN   NaN          NaN
1874           PR    total  1991         NaN   NaN          NaN
1875           PR  under18  1991         NaN   NaN          NaN
1876           PR    total  1993         NaN   NaN          NaN

In [63]:
merged['state'].unique()

<ArrowStringArray>
[              'Alaska',              'Alabama',             'Arkansas',
              'Arizona',           'California',             'Colorado',
          'Connecticut', 'District of Columbia',             'Delaware',
              'Florida',              'Georgia',               'Hawaii',
                 'Iowa',                'Idaho',             'Illinois',
              'Indiana',               'Kansas',             'Kentucky',
            'Louisiana',        'Massachusetts',             'Maryland',
                'Maine',             'Michigan',            'Minnesota',
             'Missouri',          'Mississippi',              'Montana',
       'North Carolina',         'North Dakota',             'Nebraska',
        'New Hampshire',           'New Jersey',           'New Mexico',
               'Nevada',             'New York',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
                    nan,         'Rhode Island',       'South Carolina',
         'South Dakota',            'Tennessee',                'Texas',
                 'Utah',             'Virginia',              'Vermont',
           'Washington',            'Wisconsin',        'West Virginia',
              'Wyoming']
Length: 52, dtype: str

In [64]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

<ArrowStringArray>
['PR', 'USA']
Length: 2, dtype: str

In [66]:
merged_1.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [68]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'

In [69]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state            0
abbreviation    96
dtype: int64