# Merge and Join

In [1]:
import pandas as pd
import numpy as np

## Categories of Join

### One-to-One Joins

In [10]:
df1 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'departments': ['Accounting', 'Engineering', 'Engineering', 'HR'],
})

df2 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'hire_date': [2004, 2006, 2008, 2010],
})

display(df1, df2)

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

In [12]:
df3 = pd.merge(df1, df2, on='employee')
df3

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

### Many-to-One Joins

In [13]:
df4 = pd.DataFrame({
    'departments': ['Accounting', 'Engineering', 'HR'],
    'supervisor': ['Carly', 'Guido', 'Steve'],
})

display(df3, df4)

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

   departments supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve