# Merge and Join

In [1]:
import pandas as pd
import numpy as np

## Categories of Join

### One-to-One Joins

In [10]:
df1 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'departments': ['Accounting', 'Engineering', 'Engineering', 'HR'],
})

df2 = pd.DataFrame({
    'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
    'hire_date': [2004, 2006, 2008, 2010],
})

display(df1, df2)

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

In [12]:
df3 = pd.merge(df1, df2, on='employee')
df3

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

### Many-to-One Joins

In [17]:
df4 = pd.DataFrame({
    'departments': ['Accounting', 'Engineering', 'Engineering', 'HR'],
    'supervisor': ['Carly', 'Guido', 'Steve', 'Melody'],
})

display(df3, df4)

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

   departments supervisor
0   Accounting      Carly
1  Engineering      Guido
2  Engineering      Steve
3           HR     Melody

In [18]:
df5 = pd.merge(df3, df4)
df5

  employee  departments  hire_date supervisor
0    Mercy   Accounting       2004      Carly
1     Mary  Engineering       2006      Guido
2     Mary  Engineering       2006      Steve
3     Mark  Engineering       2008      Guido
4     Mark  Engineering       2008      Steve
5  Maureen           HR       2010     Melody

### Many-to-Many Joins

In [23]:
df6 = pd.DataFrame({
    'departments': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
    'skills': ['Math', 'Software', 'Presentation', 'Math', 'Communication', 'Spreadsheet'],
})

display(df4, df6, pd.merge(df4, df6))

   departments supervisor
0   Accounting      Carly
1  Engineering      Guido
2  Engineering      Steve
3           HR     Melody

   departments         skills
0   Accounting           Math
1   Accounting       Software
2  Engineering   Presentation
3  Engineering           Math
4           HR  Communication
5           HR    Spreadsheet

   departments supervisor         skills
0   Accounting      Carly           Math
1   Accounting      Carly       Software
2  Engineering      Guido   Presentation
3  Engineering      Guido           Math
4  Engineering      Steve   Presentation
5  Engineering      Steve           Math
6           HR     Melody  Communication
7           HR     Melody    Spreadsheet

## Specification of the Merge Key

In [25]:
display(df1, df2)

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

In [28]:
display(df1, df2, pd.merge(df1, df2, on='employee'))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

  employee  hire_date
0    Mercy       2004
1     Mary       2006
2     Mark       2008
3  Maureen       2010

  employee  departments  hire_date
0    Mercy   Accounting       2004
1     Mary  Engineering       2006
2     Mark  Engineering       2008
3  Maureen           HR       2010

### The left_on and right_on Keywords

In [33]:
df3 = pd.DataFrame({
    'name': ['Bob', 'Mercy', 'Mary', 'Mark'],
    'salary': [70000, 10000, 50000, 30000]
})

display(df1, df3, pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

  employee  departments   name  salary
0    Mercy   Accounting  Mercy   10000
1     Mary  Engineering   Mary   50000
2     Mark  Engineering   Mark   30000

#### Using drop() to drop desired columns

In [36]:
display(df1, df3, pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1))

  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

  employee  departments  salary
0    Mercy   Accounting   10000
1     Mary  Engineering   50000
2     Mark  Engineering   30000

### The left_index and right_index Keywords

In [39]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

display(df1a, df2a)

          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

          hire_date
employee
Mercy          2004
Mary           2006
Mark           2008
Maureen        2010

In [40]:
display(df1a, df2a, pd.merge(df1a, df2a, left_index=True, right_index=True))

          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

          hire_date
employee
Mercy          2004
Mary           2006
Mark           2008
Maureen        2010

          departments  hire_date
employee
Mercy      Accounting       2004
Mary      Engineering       2006
Mark      Engineering       2008
Maureen            HR       2010