# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np
print(pd.__version__)
print(np.__version__)

3.0.5
2.5.1

### Step 2. Create a data dictionary that looks like the DataFrame below

In [3]:
# create a data dictionary that looks like the DataFrame below
data = {
        'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
        'hp': [45, 39, 44, 45],
        'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
        'pokedex': ['yes', 'no', 'yes', 'no'],
        'type': ['grass', 'fire', 'water', 'bug'],
}

### Step 3. Assign it to a variable called pokemon

In [4]:
### Step 3. Create a DataFrame called pokemon
pokemon = pd.DataFrame(data)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [5]:
# Reorder columns
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [7]:
# Add a new column 'place' with Pokemon habitat locations
pokemon['place'] = ['Forest', 'Mountain', 'Ocean', 'Forest']
pokemon

         name   type  hp   evolution pokedex     place
0   Bulbasaur  grass  45     Ivysaur     yes    Forest
1  Charmander   fire  39  Charmeleon      no  Mountain
2    Squirtle  water  44   Wartortle     yes     Ocean
3    Caterpie    bug  45     Metapod      no    Forest

### Step 6. Present the type of each column

In [8]:
# Display the data type of each column
print(pokemon.dtypes)

name           str
type           str
hp           int64
evolution      str
pokedex        str
place          str
dtype: object

### BONUS: Create your own question and answer it.

### BONUS: Question - Which Pokemon are in the Pokedex and have the highest HP?

In [9]:
answer = pokemon[pokemon['pokedex'] == 'yes'].sort_values('hp', ascending=False)
print("Pokemon in Pokedex sorted by HP (highest first):")
print(answer[['name', 'type', 'hp']])

Pokemon in Pokedex sorted by HP (highest first):
        name   type  hp
0  Bulbasaur  grass  45
2   Squirtle  water  44